package ucdf2307ict_oop;

import java.io.*;
import java.util.Arrays;
import javax.swing.JOptionPane;

public class LecturerLogin extends javax.swing.JFrame {
    File f = new File("LECTURER_INFO.txt");
    private String Username;

    public LecturerLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TitleLabel1 = new javax.swing.JLabel();
        TitleLabel2 = new javax.swing.JLabel();
        TitleLabel3 = new javax.swing.JLabel();
        StaffIDLabel4 = new javax.swing.JLabel();
        StaffIDTextField1 = new javax.swing.JTextField();
        PasswordLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        LoginButton1 = new javax.swing.JButton();
        TitleLabel7 = new javax.swing.JLabel();
        SignUpPageButton2 = new javax.swing.JButton();
        TitleLabel5 = new javax.swing.JLabel();
        StudentPageButton3 = new javax.swing.JButton();
        CloseButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 494));

        TitleLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        TitleLabel1.setText("APU Psychology Consultation ");

        TitleLabel2.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        TitleLabel2.setText("Management System");

        TitleLabel3.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        TitleLabel3.setText("Lecturer Log In");

        StaffIDLabel4.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        StaffIDLabel4.setText(" Staff ID     :");

        StaffIDTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                StaffIDTextField1KeyReleased(evt);
            }
        });

        PasswordLabel6.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        PasswordLabel6.setText("Password    :");

        LoginButton1.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        LoginButton1.setText("Log In");
        LoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButton1ActionPerformed(evt);
            }
        });

        TitleLabel7.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        TitleLabel7.setText("Don't have an account?");

        SignUpPageButton2.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        SignUpPageButton2.setText("Sign Up here");
        SignUpPageButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpPageButton2ActionPerformed(evt);
            }
        });

        TitleLabel5.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        TitleLabel5.setText("Not a Lecturer?");

        StudentPageButton3.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        StudentPageButton3.setText("Log in as Student");
        StudentPageButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentPageButton3ActionPerformed(evt);
            }
        });

        CloseButton1.setBackground(new java.awt.Color(255, 153, 153));
        CloseButton1.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        CloseButton1.setText("Close");
        CloseButton1.setMaximumSize(new java.awt.Dimension(25, 21));
        CloseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TitleLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(TitleLabel2))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(SignUpPageButton2))
                                        .addComponent(TitleLabel7))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(156, 156, 156)
                                            .addComponent(TitleLabel5)
                                            .addGap(33, 33, 33))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(StudentPageButton3)
                                            .addGap(14, 14, 14))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PasswordLabel6)
                                        .addComponent(StaffIDLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(StaffIDTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                        .addComponent(jPasswordField1))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(LoginButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(TitleLabel3)))
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CloseButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CloseButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(TitleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TitleLabel2)
                .addGap(18, 18, 18)
                .addComponent(TitleLabel3)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StaffIDLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel6)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(LoginButton1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TitleLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignUpPageButton2)
                    .addComponent(StudentPageButton3))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpPageButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpPageButton2ActionPerformed
        LecturerSignUp lsp = new LecturerSignUp();
        lsp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignUpPageButton2ActionPerformed

    private void LoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButton1ActionPerformed
        String inputSTFID = StaffIDTextField1.getText();
        char[] inputpassword = jPasswordField1.getPassword();
        try (BufferedReader br = new BufferedReader(new FileReader(f))){
            //Read the file to check 
            String eachLine;
            boolean isAuthenticated = false;
            while((eachLine = br.readLine()) != null){
                String values[] = eachLine.split(",");
                if (values[0].equals(inputSTFID) && Arrays.equals(values[2].toCharArray(),inputpassword)){
                    Username = values[1];
                    JOptionPane.showMessageDialog(this, "You have successfully login!");
                    LecturerDashboard ld = new LecturerDashboard(Username);
                    ld.setVisible(true);
                    isAuthenticated = true;//Mark as authenticated
                    this.dispose();
                    break;// Exit the loop once authenticated
                }   
            }
            //show error if no match was found
            if (!isAuthenticated){
                JOptionPane.showMessageDialog(this, "Incorrect Staff ID or Password!");
                StaffIDTextField1.setText("");
                jPasswordField1.setText("");
            }
        } catch (IOException e) {
             JOptionPane.showMessageDialog(this, "Error reading file: " + e.getMessage());
        }
    }//GEN-LAST:event_LoginButton1ActionPerformed

    private void StudentPageButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentPageButton3ActionPerformed
        StudentLogin sl = new StudentLogin();
        sl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StudentPageButton3ActionPerformed

    private void StaffIDTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StaffIDTextField1KeyReleased
        String inputSTFID = StaffIDTextField1.getText().toUpperCase();
        StaffIDTextField1.setText(inputSTFID);
    }//GEN-LAST:event_StaffIDTextField1KeyReleased

    private void CloseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButton1ActionPerformed
        JOptionPane.showMessageDialog(this,"Thank you for using APU Psychology Management System! \n Terminating the system......");
        this.dispose();
    }//GEN-LAST:event_CloseButton1ActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton1;
    private javax.swing.JButton LoginButton1;
    private javax.swing.JLabel PasswordLabel6;
    private javax.swing.JButton SignUpPageButton2;
    private javax.swing.JLabel StaffIDLabel4;
    private javax.swing.JTextField StaffIDTextField1;
    private javax.swing.JButton StudentPageButton3;
    private javax.swing.JLabel TitleLabel1;
    private javax.swing.JLabel TitleLabel2;
    private javax.swing.JLabel TitleLabel3;
    private javax.swing.JLabel TitleLabel5;
    private javax.swing.JLabel TitleLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
