
package ucdf2307ict_oop;

import java.io.*;
import javax.swing.JOptionPane;

public class LecturerSignUp extends javax.swing.JFrame {
    File f = new File("LECTURER_INFO.txt");
    private String newStaffID;
    private String Username;
    public LecturerSignUp() {
        generateNewStaffID();//Ensure newStaffID is set before initializing components
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TitleLabel1 = new javax.swing.JLabel();
        TitleLabel2 = new javax.swing.JLabel();
        TitleLabel3 = new javax.swing.JLabel();
        TitleLabel4 = new javax.swing.JLabel();
        StaffIDTextField1 = new javax.swing.JTextField();
        TitleLabel5 = new javax.swing.JLabel();
        UsernameTextField2 = new javax.swing.JTextField();
        TitleLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        SignUpButton1 = new javax.swing.JButton();
        TitleLabel7 = new javax.swing.JLabel();
        LoginPageButton2 = new javax.swing.JButton();
        CloseButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        TitleLabel1.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        TitleLabel1.setText("APU Psychology Consultation ");

        TitleLabel2.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        TitleLabel2.setText("Management System");

        TitleLabel3.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        TitleLabel3.setText("Lecturer Sign Up");

        TitleLabel4.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        TitleLabel4.setText("Staff ID   :");

        StaffIDTextField1.setEditable(false);
        StaffIDTextField1.setText(newStaffID);

        TitleLabel5.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        TitleLabel5.setText("Username :");

        UsernameTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UsernameTextField2KeyReleased(evt);
            }
        });

        TitleLabel6.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        TitleLabel6.setText("Password  :");

        SignUpButton1.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        SignUpButton1.setText("Sign Up");
        SignUpButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButton1ActionPerformed(evt);
            }
        });

        TitleLabel7.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        TitleLabel7.setText("Already have an account?");

        LoginPageButton2.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        LoginPageButton2.setText("Log in now");
        LoginPageButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPageButton2ActionPerformed(evt);
            }
        });

        CloseButton1.setBackground(new java.awt.Color(255, 153, 153));
        CloseButton1.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        CloseButton1.setText("Close");
        CloseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TitleLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(TitleLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TitleLabel5)
                                    .addComponent(TitleLabel6)
                                    .addComponent(TitleLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPasswordField1)
                                        .addComponent(UsernameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(StaffIDTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(TitleLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(LoginPageButton2))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(SignUpButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(TitleLabel3)))
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CloseButton1)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(CloseButton1)
                .addGap(18, 18, 18)
                .addComponent(TitleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TitleLabel2)
                .addGap(18, 18, 18)
                .addComponent(TitleLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TitleLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StaffIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TitleLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UsernameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleLabel6)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SignUpButton1)
                .addGap(18, 18, 18)
                .addComponent(TitleLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginPageButton2)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateNewStaffID(){
        newStaffID = "STF001";
        String lastStaffID = null;
            try (BufferedReader br = new BufferedReader(new FileReader(f))){
                String line;
                while ((line = br.readLine()) != null){
                    lastStaffID = line.split(",")[0];//Assume Staff ID is the first value
                }
            }catch (IOException e){
                JOptionPane.showMessageDialog(this, "Error reading file: " + e.getMessage());
            }
            
            int number;
            if (lastStaffID != null){
                number = Integer.parseInt(lastStaffID.substring(3));//Extract the number part
                newStaffID = String.format("STF%03d", number + 1 );//Increment and format
            }
    }
    private void LoginPageButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPageButton2ActionPerformed
        LecturerLogin ll = new LecturerLogin();
        ll.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginPageButton2ActionPerformed

    private void SignUpButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButton1ActionPerformed
        StaffIDTextField1.setText(newStaffID);
        Username = UsernameTextField2.getText().toUpperCase();
        char[] password = jPasswordField1.getPassword();
        
        if (Username.isEmpty() || password.length == 0){
            JOptionPane.showMessageDialog(this, "Please fill in your information details");
            return;
        }

        if (Username.isEmpty()){
            JOptionPane.showMessageDialog(this, "Username cannot be empty!");
            return;
        }
        if (password.length == 0) {
            JOptionPane.showMessageDialog(this, "Password cannot be empty");
            return;
        }
        if (password.length < 8){
            JOptionPane.showMessageDialog(this, "Password must be 8 character!");
            return;// Prevent further execution
        }
        
        generateNewStaffID();//Generate or refresh Staff ID
        StaffIDTextField1.setText(newStaffID);
        
        try{
            //Check if lecturerinfo.txt exists
            //if lecturerinfo.txt does not exists, create one
            if (!f.exists()){
                f.createNewFile();
            }
            
            //Check if Staff ID already exists
            try(BufferedReader br = new BufferedReader(new FileReader(f))){
                //Read the file to check if StaffID exists
                String eachLine;

                while((eachLine = br.readLine()) != null){
                    String values[] = eachLine.split(",");
                    if (values[1].equals(Username)){
                        JOptionPane.showMessageDialog(this, "Username already exists. Please try with another Username.");
                        StaffIDTextField1.setText(newStaffID);
                        UsernameTextField2.setText("");
                        jPasswordField1.setText("");
                        return;
                    }
                }  
                
            } catch (IOException e){
                JOptionPane.showMessageDialog(this, "An error occured while checking the Staff ID");
                return;
            }
            
            //write data to the file 
            try (FileWriter fw = new FileWriter(f, true); BufferedWriter bw = new BufferedWriter(fw)){
                String passwordStr = new String(password);
                bw.write(newStaffID+","+Username+","+passwordStr+"\n");
                bw.close();
            }catch (IOException e) {
                JOptionPane.showMessageDialog(this, "An error occurred while writing to the file.");
                return;
            }
            
            //display welcome message
            JOptionPane.showMessageDialog(this, "Registered successfully! Your Staff ID is "+newStaffID+". Please Log In now.");
            LecturerLogin ll = new LecturerLogin();
            ll.setVisible(true);
            this.dispose();
            
            //clear the text fields after sign up
            StaffIDTextField1.setText(newStaffID);
            UsernameTextField2.setText("");
            jPasswordField1.setText("");
        } catch (IOException e){
            JOptionPane.showMessageDialog(this, "An error occured while writing to the file.");
        }
    }//GEN-LAST:event_SignUpButton1ActionPerformed

    private void UsernameTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsernameTextField2KeyReleased
        String username = UsernameTextField2.getText().toUpperCase();
        UsernameTextField2.setText(username);
    }//GEN-LAST:event_UsernameTextField2KeyReleased

    private void CloseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButton1ActionPerformed
        JOptionPane.showMessageDialog(this,"Thank you for using APU Psychology Management System! \n Terminating the system......");
        this.dispose();
    }//GEN-LAST:event_CloseButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturerSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new LecturerSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton1;
    private javax.swing.JButton LoginPageButton2;
    private javax.swing.JButton SignUpButton1;
    private javax.swing.JTextField StaffIDTextField1;
    private javax.swing.JLabel TitleLabel1;
    private javax.swing.JLabel TitleLabel2;
    private javax.swing.JLabel TitleLabel3;
    private javax.swing.JLabel TitleLabel4;
    private javax.swing.JLabel TitleLabel5;
    private javax.swing.JLabel TitleLabel6;
    private javax.swing.JLabel TitleLabel7;
    private javax.swing.JTextField UsernameTextField2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
