package ucdf2307ict_oop;

import java.io.*;
import java.util.*;
import javax.swing.JOptionPane;

public class StudentLogin extends javax.swing.JFrame {
    private String studentID;

    public StudentLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        APUPsychologyConsultationLabel = new javax.swing.JLabel();
        ManagementSystemLabel = new javax.swing.JLabel();
        LoginLabel = new javax.swing.JLabel();
        StudentIDLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        StudentIDTextField = new javax.swing.JTextField();
        StudentPasswordTextField = new javax.swing.JPasswordField();
        SignUpButton = new javax.swing.JButton();
        CheckAccountLabel = new javax.swing.JLabel();
        CheckStudentLabel = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        DirectLecturerSiteButton = new javax.swing.JButton();
        forgotPasswordbutton = new javax.swing.JButton();
        terminateSystemButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        APUPsychologyConsultationLabel.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        APUPsychologyConsultationLabel.setText("APU Psychology Consultation");

        ManagementSystemLabel.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        ManagementSystemLabel.setText("Management System");

        LoginLabel.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        LoginLabel.setText("Log In");

        StudentIDLabel.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        StudentIDLabel.setText("Student ID :");

        PasswordLabel.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        PasswordLabel.setText("Password    :");

        SignUpButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        SignUpButton.setText("Sign up here");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        CheckAccountLabel.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        CheckAccountLabel.setText("Don't have an account?");

        CheckStudentLabel.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        CheckStudentLabel.setText("Not a student?");

        LoginButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        LoginButton.setText("Log In");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        DirectLecturerSiteButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        DirectLecturerSiteButton.setText("Log in as lecturer");
        DirectLecturerSiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectLecturerSiteButtonActionPerformed(evt);
            }
        });

        forgotPasswordbutton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        forgotPasswordbutton.setText("Forgot password");
        forgotPasswordbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPasswordbuttonActionPerformed(evt);
            }
        });

        terminateSystemButton.setBackground(new java.awt.Color(255, 0, 51));
        terminateSystemButton.setFont(new java.awt.Font("Modern No. 20", 1, 12)); // NOI18N
        terminateSystemButton.setForeground(new java.awt.Color(255, 255, 255));
        terminateSystemButton.setText("Terminate");
        terminateSystemButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        terminateSystemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminateSystemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(ManagementSystemLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(CheckStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SignUpButton)
                                .addGap(151, 151, 151)
                                .addComponent(DirectLecturerSiteButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CheckAccountLabel)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(StudentIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StudentIDTextField)
                            .addComponent(StudentPasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(LoginButton)))))
                .addGap(106, 255, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(APUPsychologyConsultationLabel)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LoginLabel)
                        .addGap(410, 410, 410))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(forgotPasswordbutton)
                        .addGap(389, 389, 389))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(terminateSystemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(terminateSystemButton)
                .addGap(11, 11, 11)
                .addComponent(APUPsychologyConsultationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManagementSystemLabel)
                .addGap(18, 18, 18)
                .addComponent(LoginLabel)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentIDLabel)
                    .addComponent(StudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(StudentPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(LoginButton)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckAccountLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CheckStudentLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DirectLecturerSiteButton)
                    .addComponent(SignUpButton))
                .addGap(18, 18, 18)
                .addComponent(forgotPasswordbutton)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String studentID = StudentIDTextField.getText();
        String password = new String(StudentPasswordTextField.getPassword());
        
        // Validate input fields
        if (studentID.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Create temporary Student object for ID validation
        Student tempStudent = new Student(studentID, "", "");
        
        // Validate student ID format
        if (!tempStudent.validateId()) {
            JOptionPane.showMessageDialog(this, 
                "Invalid Student ID format.\nMust start with 'TP' followed by 6 numbers", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            StudentIDTextField.setText("");
            return;
        }
        
        // Find student in database
        Student student = Student.findStudent(studentID);
        if (student == null) {
            JOptionPane.showMessageDialog(this, 
                "Student ID not found.\nPlease sign up if you don't have an account.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            StudentIDTextField.setText("");
            StudentPasswordTextField.setText("");
            return;
        }

        // Validate password
        if (!student.authenticate(password)) {
            JOptionPane.showMessageDialog(this, 
                "Incorrect password.\nPlease try again.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            StudentPasswordTextField.setText("");
            return;
        }

        // Login successful
        JOptionPane.showMessageDialog(this, 
            "Welcome back, " + student.getUsername() + "!", 
            "Login Successful!", 
            JOptionPane.INFORMATION_MESSAGE);

        // Navigate to main page
        StudentDashboard sd = new StudentDashboard(studentID);
        sd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        StudentSignUp ssu = new StudentSignUp(studentID);
        ssu.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void DirectLecturerSiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectLecturerSiteButtonActionPerformed
        LecturerLogin ll = new LecturerLogin();
        ll.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DirectLecturerSiteButtonActionPerformed

    private void forgotPasswordbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPasswordbuttonActionPerformed
        StudentForgotPassword sfp = new StudentForgotPassword(studentID);
        sfp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_forgotPasswordbuttonActionPerformed

    private void terminateSystemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminateSystemButtonActionPerformed
        JOptionPane.showMessageDialog(this, 
                "Thank you for using APU Psychology Management System! \n Terminating the system......");
        this.dispose();
    }//GEN-LAST:event_terminateSystemButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APUPsychologyConsultationLabel;
    private javax.swing.JLabel CheckAccountLabel;
    private javax.swing.JLabel CheckStudentLabel;
    private javax.swing.JButton DirectLecturerSiteButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JLabel ManagementSystemLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel StudentIDLabel;
    private javax.swing.JTextField StudentIDTextField;
    private javax.swing.JPasswordField StudentPasswordTextField;
    private javax.swing.JButton forgotPasswordbutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton terminateSystemButton;
    // End of variables declaration//GEN-END:variables
}
