package ucdf2307ict_oop;

import java.io.*;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class StudentSignUp extends javax.swing.JFrame {
    private String studentID;

    public StudentSignUp(String studentID) {
        this.studentID = studentID;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        APUPsychologyConsultationLabel = new javax.swing.JLabel();
        ManagementSystemLabel = new javax.swing.JLabel();
        SignUpLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        StudentUsernameTextField = new javax.swing.JTextField();
        StudentPasswordTextField = new javax.swing.JPasswordField();
        StudentSignUpButton = new javax.swing.JButton();
        CheckAccountLabel = new javax.swing.JLabel();
        DirectStudentLogInPageButton = new javax.swing.JButton();
        StudentIDLabel = new javax.swing.JLabel();
        StudentIDTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        APUPsychologyConsultationLabel.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        APUPsychologyConsultationLabel.setText("APU Psychology Consultation");

        ManagementSystemLabel.setFont(new java.awt.Font("Modern No. 20", 1, 36)); // NOI18N
        ManagementSystemLabel.setText("Management System");

        SignUpLabel.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        SignUpLabel.setText("Sign Up");

        UsernameLabel.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        UsernameLabel.setText("Username   :");

        PasswordLabel.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        PasswordLabel.setText("Password    :");

        StudentUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentUsernameTextFieldActionPerformed(evt);
            }
        });

        StudentSignUpButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        StudentSignUpButton.setText("Sign Up");
        StudentSignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentSignUpButtonActionPerformed(evt);
            }
        });

        CheckAccountLabel.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        CheckAccountLabel.setText("Already have an account?");

        DirectStudentLogInPageButton.setFont(new java.awt.Font("Modern No. 20", 0, 12)); // NOI18N
        DirectStudentLogInPageButton.setText("Log in now");
        DirectStudentLogInPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectStudentLogInPageButtonActionPerformed(evt);
            }
        });

        StudentIDLabel.setFont(new java.awt.Font("Modern No. 20", 1, 24)); // NOI18N
        StudentIDLabel.setText("Student ID :");

        StudentIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(ManagementSystemLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StudentIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StudentUsernameTextField)
                            .addComponent(StudentPasswordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(StudentIDTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(StudentSignUpButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(SignUpLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(CheckAccountLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(DirectStudentLogInPageButton)))
                .addGap(247, 247, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addComponent(APUPsychologyConsultationLabel)
                .addGap(219, 219, 219))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(APUPsychologyConsultationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManagementSystemLabel)
                .addGap(18, 18, 18)
                .addComponent(SignUpLabel)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentIDLabel)
                    .addComponent(StudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabel)
                    .addComponent(StudentUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(StudentPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(StudentSignUpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(CheckAccountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DirectStudentLogInPageButton)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentUsernameTextFieldActionPerformed

    private void DirectStudentLogInPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectStudentLogInPageButtonActionPerformed
        StudentLogin sl = new StudentLogin();
        sl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DirectStudentLogInPageButtonActionPerformed

    private void StudentIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentIDTextFieldActionPerformed

    private void StudentSignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentSignUpButtonActionPerformed
        String studentID = StudentIDTextField.getText();
        String username = StudentUsernameTextField.getText();
        String password = new String(StudentPasswordTextField.getPassword());
        
        // Check if any input fields are empty
        if (studentID.isEmpty() && username.isEmpty() && password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill in your details");
            return; // Stop further execution if fields are empty
        }
        
        // Create Student object for validation
        Student student = new Student(studentID, username, password);

        // Validate student ID format
        if (!student.validateId()) {
            JOptionPane.showMessageDialog(this, "Student ID must start with 'TP' followed by 6 numbers");
            clearFields();
            return;
        }

        // Validate password requirements
        if (!student.validatePassword()) {
            JOptionPane.showMessageDialog(this, "Password must contain:\n" +
                                              "- At least one uppercase letter\n" +
                                              "- At least one lowercase letter\n" +
                                              "- At least one special symbol");
            StudentPasswordTextField.setText("");
            return;
        }
        
        // append data to the file
        try{
            // check if studentinfo.txt exists
            File studentInfo = new File("studentInfo.txt");
            // if studentinfo.txt does not exist, create one
            if(!studentInfo.exists()){
                studentInfo.createNewFile();
            }
            
            // Check if student ID already exists
            try {
                    // Read the file to check if studentID exists
                    Scanner sc = new Scanner(studentInfo); // initialize a scanner
                    while (sc.hasNextLine()) { // loop through each line in file until no more lines left
                        String line = sc.nextLine(); // reads a line
                        String[] details = line.split(","); // stores each part into an array, details
                        String existingStudentID = details[0]; // assume studentID is the first value in each line

                        if (details[0].equals(student.getId())) {
                            JOptionPane.showMessageDialog(this, "Student ID already exists. Please try with another student ID.");
                            clearFields();
                            return;
                        }
                    }
                    sc.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "An error occurred while checking the student ID.");
                return;
            }
            
            // write data to the file - only one write operation
            try (FileWriter fw = new FileWriter(studentInfo, true)) {
                fw.write(student.getId() + "," + 
                            student.getUsername() + "," + 
                            student.getPassword() + 
                            System.lineSeparator());
                
                JOptionPane.showMessageDialog(this, "Registered successfully! Please log in now.");

                // Direct to login page
                StudentLogin sl = new StudentLogin();
                sl.setVisible(true);
                this.dispose();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "An error occurred while writing to the file.");
            }
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while writing to the file.");
        }
    }//GEN-LAST:event_StudentSignUpButtonActionPerformed
    
    private void clearFields() {
        StudentIDTextField.setText("");
        StudentUsernameTextField.setText("");
        StudentPasswordTextField.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new StudentSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APUPsychologyConsultationLabel;
    private javax.swing.JLabel CheckAccountLabel;
    private javax.swing.JButton DirectStudentLogInPageButton;
    private javax.swing.JLabel ManagementSystemLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel SignUpLabel;
    private javax.swing.JLabel StudentIDLabel;
    private javax.swing.JTextField StudentIDTextField;
    private javax.swing.JPasswordField StudentPasswordTextField;
    private javax.swing.JButton StudentSignUpButton;
    private javax.swing.JTextField StudentUsernameTextField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
